# SPARK ETL - BẢNG PHỤ, TỐI ƯU & BENCHMARK

## PHẦN 1: KẾT NỐI SPARK VÀ HDFS

In [1]:
from pyspark.sql import SparkSession, functions as F, Window

BASE = "hdfs://namenode:8020"
spark = (SparkSession.builder.appName("giai-doan-4")
         .config("spark.hadoop.fs.defaultFS", BASE)
         .config("spark.sql.warehouse.dir", f"{BASE}/user/hive/warehouse")
         .config("hive.metastore.uris", "thrift://hive-metastore:9083")
         .config("spark.sql.parquet.writeLegacyFormat", "true")   # de Hive 2.3 doc duoc
         .config("spark.driver.memory", "3g")
         .config("spark.sql.shuffle.partitions", "16")
         .config("spark.hadoop.dfs.replication", "1")
         .config("spark.local.dir", "/tmp/spark")
         .enableHiveSupport().getOrCreate())

spark.sql("CREATE DATABASE IF NOT EXISTS fifa")
# Kiểm tra phiên bản Spark xem đã kết nối thành công chưa
print("Spark version:", spark.version)

Spark version: 3.5.0

In [2]:
print(spark.conf.get("spark.hadoop.dfs.replication", "chưa đặt"))
print(spark.conf.get("spark.local.dir"))

1
/tmp/spark

## PHẦN 2: ĐỌC VÀ KIỂM TRA DỮ LIỆU TỪ HDFS
### Bước 1: Đọc dữ liệu cầu thủ từ HDFS vào Spark DataFrame

In [3]:
# Đọc file male_players.csv từ HDFS
df_male = spark.read.option("header", "true") \
                    .option("inferSchema", "true") \
                    .csv("hdfs://namenode:8020/fifa/raw/players/gender=male/male_players.csv")

# Kiểm tra số lượng dòng và hiển thị 5 dòng đầu tiên
print("Tổng số cầu thủ nam:", df_male.count())
df_male.show(5)

Tổng số cầu thủ nam: 10003590
+---------+--------------------+------------+-----------+----------------+--------------+--------------------+----------------+-------+---------+---------+--------+---+----------+---------+---------+---------+--------------+------------+------------+-------------------+-------------+------------------+----------------+----------------+------------------------------+--------------+----------------+--------------+---------------+--------------------+--------------+---------+-----------+------------------------+-------------+----------------+---------+------------------+--------------------+--------------------+----+--------+-------+---------+---------+------+------------------+-------------------+--------------------------+-----------------------+-----------------+---------------+-----------+-----------------+------------------+------------------+---------------------+---------------------+----------------+------------------+----------------+----------------+-------------+-------------+--------------+----------------+--------------------+-----------------------+---------------------+----------------+-------------------+-------------------+---------------------------+-------------------------+------------------------+------------------+--------------------+-------------------+-----------------------+--------------------+-----------------+----+----+----+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+--------------------+
|player_id|          player_url|fifa_version|fifa_update|fifa_update_date|    short_name|           long_name|player_positions|overall|potential|value_eur|wage_eur|age|       dob|height_cm|weight_kg|league_id|   league_name|league_level|club_team_id|          club_name|club_position|club_jersey_number|club_loaned_from|club_joined_date|club_contract_valid_until_year|nationality_id|nationality_name|nation_team_id|nation_position|nation_jersey_number|preferred_foot|weak_foot|skill_moves|international_reputation|    work_rate|       body_type|real_face|release_clause_eur|         player_tags|       player_traits|pace|shooting|passing|dribbling|defending|physic|attacking_crossing|attacking_finishing|attacking_heading_accuracy|attacking_short_passing|attacking_volleys|skill_dribbling|skill_curve|skill_fk_accuracy|skill_long_passing|skill_ball_control|movement_acceleration|movement_sprint_speed|movement_agility|movement_reactions|movement_balance|power_shot_power|power_jumping|power_stamina|power_strength|power_long_shots|mentality_aggression|mentality_interceptions|mentality_positioning|mentality_vision|mentality_penalties|mentality_composure|defending_marking_awareness|defending_standing_tackle|defending_sliding_tackle|goalkeeping_diving|goalkeeping_handling|goalkeeping_kicking|goalkeeping_positioning|goalkeeping_reflexes|goalkeeping_speed|  ls|  st|  rs| lw| lf| cf| rf| rw| lam| cam| ram|  lm| lcm|  cm| rcm|  rm| lwb| ldm| cdm| rdm| rwb|  lb| lcb|  cb| rcb|  rb|  gk|     player_face_url|
+---------+--------------------+------------+-----------+----------------+--------------+--------------------+----------------+-------+---------+---------+--------+---+----------+---------+---------+---------+--------------+------------+------------+-------------------+-------------+------------------+----------------+----------------+------------------------------+--------------+----------------+--------------+---------------+--------------------+--------------+---------+-----------+------------------------+-------------+----------------+---------+------------------+--------------------+--------------------+----+--------+-------+---------+---------+------+------------------+-------------------+--------------------------+-----------------------+-----------------+---------------+-----------+-----------------+------------------+------------------+---------------------+---------------------+----------------+------------------+----------------+----------------+-------------+-------------+--------------+----------------+--------------------+-----------------------+---------------------+----------------+-------------------+-------------------+---------------------------+-------------------------+------------------------+------------------+--------------------+-------------------+-----------------------+--------------------+-----------------+----+----+----+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+--------------------+
|   158023|/player/158023/li...|          23|          9|      2023-01-13|      L. Messi|Lionel Andrés Mes...|              RW|     91|       91| 54000000|  195000| 35|1987-06-24|      169|       67|       16|       Ligue 1|           1|          73|Paris Saint Germain|           RS|                30|            NULL|      2021-08-10|                          2023|            52|       Argentina|          1369|             RW|                  10|          Left|        4|          4|                       5|      Low/Low|          Unique|      Yes|          99900000|#Dribbler, #Dista...|Finesse Shot, Lon...|  81|      89|     90|       94|       34|    64|                84|                 90|                        70|                     91|               88|             95|         93|               93|                90|                93|                   87|                   76|              91|                92|              95|              86|           68|           70|            68|              91|                  44|                     40|                   93|              94|                 75|                 96|                         20|                       35|                      24|                 6|                  11|                 15|                     14|                   8|             NULL|87+3|87+3|87+3| 90| 91| 91| 91| 90|92-1|92-1|92-1|89+2|85+3|85+3|85+3|89+2|64+3|63+3|63+3|63+3|64+3|59+3|50+3|50+3|50+3|59+3|19+3|https://cdn.sofif...|
|   165153|/player/165153/ka...|          23|          9|      2023-01-13|    K. Benzema|       Karim Benzema|          CF, ST|     91|       91| 64000000|  450000| 34|1987-12-19|      185|       81|       53|       La Liga|           1|         243|        Real Madrid|           CF|                 9|            NULL|      2009-07-09|                          2023|            18|          France|          NULL|           NULL|                NULL|         Right|        4|          4|                       4|Medium/Medium|Normal (170-185)|      Yes|         131200000|#Poacher, #Clinic...|Leadership, Fines...|  80|      88|     83|       87|       39|    78|                75|                 92|                        90|                     89|               88|             87|         82|               73|                76|                91|                   79|                   80|              78|                92|              72|              87|           79|           82|            82|              80|                  63|                     39|                   92|              89|                 84|                 90|                         43|                       24|                      18|                13|                  11|                  5|                      5|                   7|             NULL|89+2|89+2|89+2| 87| 89| 89| 89| 87|88+3|88+3|88+3|86+3|81+3|81+3|81+3|86+3|64+3|64+3|64+3|64+3|64+3|60+3|55+3|55+3|55+3|60+3|18+3|https://cdn.sofif...|
|   188545|/player/188545/ro...|          23|          9|      2023-01-13|R. Lewandowski|  Robert Lewandowski|              ST|     91|       91| 84000000|  420000| 33|1988-08-21|      185|       81|       53|       La Liga|           1|         241|       FC Barcelona|           ST|                 9|            NULL|      2022-07-18|                          2025|            37|          Poland|          1353|             ST|                   9|         Right|        4|          4|                       5|  High/Medium|          Unique|      Yes|         172200000|#Aerial Threat, #...|Solid Player, Fin...|  75|      91|     79|       86|       44|    83|                71|                 94|                        91|                     84|               89|             85|         79|               85|                70|                89|                   76|                   75|              77|                93|              82|              91|           85|           76|            87|              84|                  81|                     49|                   94|              81|                 90|                 88|                         35|                       42|                      19|                15|                   6|                 12|                      8|                  10|             NULL|89+2|89+2|89+2| 85| 88| 88| 88| 85|85+3|85+3|85+3|83+3|80+3|80+3|80+3|83+3|64+3|66+3|66+3|66+3|64+3|61+3|60+3|60+3|60+3|61+3|19+3|https://cdn.sofif...|
|   192985|/player/192985/ke...|          23|          9|      2023-01-13|  K. De Bruyne|     Kevin De Bruyne|         CM, CAM|     91|       91|107500000|  350000| 31|1991-06-28|      181|       75|       13|Premier League|           1|          10|    Manchester City|          RCM|                17|            NULL|      2015-08-30|                          2025|             7|         Belgium|          1325|             RF|                   7|         Right|        5|          4|                       4|  High/Medium|          Unique|      Yes|         198900000|#Dribbler, #Playm...|Injury Prone, Lea...|  74|      88|     93|       87|       63|    77|                94|                 85|                        55|                     93|               83|             87|         89|               83|                93|                90|                   76|                   73|              76|                91|              78|              92|           63|           89|            74|              91|                  75|                     64|                   88|              94|                 83|                 89|                         65|                       65|                      53|                15|                  13|                  5|                     10|                  13|             NULL|83+3|83+3|83+3| 87| 87| 87| 87| 87|89+2|89+2|89+2|88+3|89+2|89+2|89+2|88+3|78+3|79+3|79+3|79+3|78+3|74+3|68+3|68+3|68+3|74+3|21+3|https://cdn.sofif...|
|   231747|/player/231747/ky...|          23|          9|      2023-01-13|     K. Mbappé|Kylian Mbappé Lottin|          ST, LW|     91|       95|190500000|  230000| 23|1998-12-20|      182|       73|       16|       Ligue 1|           1|          73|Paris Saint Germain|           LS|                 7|            NULL|      2018-07-01|                          2024|            18|          France|          1335|             LW|                  10|         Right|        4|          5|                       4|     High/Low|          Unique|      Yes|         366700000|#Speedster, #Drib...|Solid Player, Fla...|  97|      89|     80|       92|       36|    76|                78|                 93|                        72|                     85|               83|             93|         80|               69|                71|                91|                   97|                   97|              93|                93|              81|              88|           77|           87|            76|              82|                  64|                     38|                   92|              83|                 80|                 88|                         26|                       34|                      32|                13|                   5|                  7|                     11|                   6|             NULL|89+3|89+3|89+3| 90| 90| 90| 90| 90|89+3|89+3|89+3|89+3|81+3|81+3|81+3|89+3|67+3|63+3|63+3|63+3|67+3|63+3|54+3|54+3|54+3|63+3|18+3|https://cdn.sofif...|
+---------+--------------------+------------+-----------+----------------+--------------+--------------------+----------------+-------+---------+---------+--------+---+----------+---------+---------+---------+--------------+------------+------------+-------------------+-------------+------------------+----------------+----------------+------------------------------+--------------+----------------+--------------+---------------+--------------------+--------------+---------+-----------+------------------------+-------------+----------------+---------+------------------+--------------------+--------------------+----+--------+-------+---------+---------+------+------------------+-------------------+--------------------------+-----------------------+-----------------+---------------+-----------+-----------------+------------------+------------------+---------------------+---------------------+----------------+------------------+----------------+----------------+-------------+-------------+--------------+----------------+--------------------+-----------------------+---------------------+----------------+-------------------+-------------------+---------------------------+-------------------------+------------------------+------------------+--------------------+-------------------+-----------------------+--------------------+-----------------+----+----+----+---+---+---+---+---+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+--------------------+
only showing top 5 rows

In [4]:
#Chuyển sang dạng xem theo chiều dọc (dễ nhìn toàn bộ chi tiết của 1-2 cầu thủ)
df_male.show(2, vertical=True, truncate=False)

-RECORD 0----------------------------------------------------------------------------------------------------------------------------------------
 player_id                      | 158023
 player_url                     | /player/158023/lionel-messi/230009
 fifa_version                   | 23
 fifa_update                    | 9
 fifa_update_date               | 2023-01-13
 short_name                     | L. Messi
 long_name                      | Lionel Andrés Messi Cuccittini
 player_positions               | RW
 overall                        | 91
 potential                      | 91
 value_eur                      | 54000000
 wage_eur                       | 195000
 age                            | 35
 dob                            | 1987-06-24
 height_cm                      | 169
 weight_kg                      | 67
 league_id                      | 16
 league_name                    | Ligue 1
 league_level                   | 1
 club_team_id                   | 73
 club_name                      | Paris Saint Germain
 club_position                  | RS
 club_jersey_number             | 30
 club_loaned_from               | NULL
 club_joined_date               | 2021-08-10
 club_contract_valid_until_year | 2023
 nationality_id                 | 52
 nationality_name               | Argentina
 nation_team_id                 | 1369
 nation_position                | RW
 nation_jersey_number           | 10
 preferred_foot                 | Left
 weak_foot                      | 4
 skill_moves                    | 4
 international_reputation       | 5
 work_rate                      | Low/Low
 body_type                      | Unique
 real_face                      | Yes
 release_clause_eur             | 99900000
 player_tags                    | #Dribbler, #Distance Shooter, #FK Specialist, #Acrobat, #Clinical Finisher, #Complete Forward
 player_traits                  | Finesse Shot, Long Shot Taker (AI), Playmaker (AI), Outside Foot Shot, Chip Shot (AI), Technical Dribbler (AI)
 pace                           | 81
 shooting                       | 89
 passing                        | 90
 dribbling                      | 94
 defending                      | 34
 physic                         | 64
 attacking_crossing             | 84
 attacking_finishing            | 90
 attacking_heading_accuracy     | 70
 attacking_short_passing        | 91
 attacking_volleys              | 88
 skill_dribbling                | 95
 skill_curve                    | 93
 skill_fk_accuracy              | 93
 skill_long_passing             | 90
 skill_ball_control             | 93
 movement_acceleration          | 87
 movement_sprint_speed          | 76
 movement_agility               | 91
 movement_reactions             | 92
 movement_balance               | 95
 power_shot_power               | 86
 power_jumping                  | 68
 power_stamina                  | 70
 power_strength                 | 68
 power_long_shots               | 91
 mentality_aggression           | 44
 mentality_interceptions        | 40
 mentality_positioning          | 93
 mentality_vision               | 94
 mentality_penalties            | 75
 mentality_composure            | 96
 defending_marking_awareness    | 20
 defending_standing_tackle      | 35
 defending_sliding_tackle       | 24
 goalkeeping_diving             | 6
 goalkeeping_handling           | 11
 goalkeeping_kicking            | 15
 goalkeeping_positioning        | 14
 goalkeeping_reflexes           | 8
 goalkeeping_speed              | NULL
 ls                             | 87+3
 st                             | 87+3
 rs                             | 87+3
 lw                             | 90
 lf                             | 91
 cf                             | 91
 rf                             | 91
 rw                             | 90
 lam                            | 92-1
 cam                            | 92-1
 ram                            | 92-1
 lm                             | 89+2
 lcm                            | 85+3
 cm                             | 85+3
 rcm                            | 85+3
 rm                             | 89+2
 lwb                            | 64+3
 ldm                            | 63+3
 cdm                            | 63+3
 rdm                            | 63+3
 rwb                            | 64+3
 lb                             | 59+3
 lcb                            | 50+3
 cb                             | 50+3
 rcb                            | 50+3
 rb                             | 59+3
 gk                             | 19+3
 player_face_url                | https://cdn.sofifa.net/players/158/023/23_120.png
-RECORD 1----------------------------------------------------------------------------------------------------------------------------------------
 player_id                      | 165153
 player_url                     | /player/165153/karim-benzema/230009
 fifa_version                   | 23
 fifa_update                    | 9
 fifa_update_date               | 2023-01-13
 short_name                     | K. Benzema
 long_name                      | Karim Benzema
 player_positions               | CF, ST
 overall                        | 91
 potential                      | 91
 value_eur                      | 64000000
 wage_eur                       | 450000
 age                            | 34
 dob                            | 1987-12-19
 height_cm                      | 185
 weight_kg                      | 81
 league_id                      | 53
 league_name                    | La Liga
 league_level                   | 1
 club_team_id                   | 243
 club_name                      | Real Madrid
 club_position                  | CF
 club_jersey_number             | 9
 club_loaned_from               | NULL
 club_joined_date               | 2009-07-09
 club_contract_valid_until_year | 2023
 nationality_id                 | 18
 nationality_name               | France
 nation_team_id                 | NULL
 nation_position                | NULL
 nation_jersey_number           | NULL
 preferred_foot                 | Right
 weak_foot                      | 4
 skill_moves                    | 4
 international_reputation       | 4
 work_rate                      | Medium/Medium
 body_type                      | Normal (170-185)
 real_face                      | Yes
 release_clause_eur             | 131200000
 player_tags                    | #Poacher, #Clinical Finisher
 player_traits                  | Leadership, Finesse Shot, Playmaker (AI), Outside Foot Shot, Team Player
 pace                           | 80
 shooting                       | 88
 passing                        | 83
 dribbling                      | 87
 defending                      | 39
 physic                         | 78
 attacking_crossing             | 75
 attacking_finishing            | 92
 attacking_heading_accuracy     | 90
 attacking_short_passing        | 89
 attacking_volleys              | 88
 skill_dribbling                | 87
 skill_curve                    | 82
 skill_fk_accuracy              | 73
 skill_long_passing             | 76
 skill_ball_control             | 91
 movement_acceleration          | 79
 movement_sprint_speed          | 80
 movement_agility               | 78
 movement_reactions             | 92
 movement_balance               | 72
 power_shot_power               | 87
 power_jumping                  | 79
 power_stamina                  | 82
 power_strength                 | 82
 power_long_shots               | 80
 mentality_aggression           | 63
 mentality_interceptions        | 39
 mentality_positioning          | 92
 mentality_vision               | 89
 mentality_penalties            | 84
 mentality_composure            | 90
 defending_marking_awareness    | 43
 defending_standing_tackle      | 24
 defending_sliding_tackle       | 18
 goalkeeping_diving             | 13
 goalkeeping_handling           | 11
 goalkeeping_kicking            | 5
 goalkeeping_positioning        | 5
 goalkeeping_reflexes           | 7
 goalkeeping_speed              | NULL
 ls                             | 89+2
 st                             | 89+2
 rs                             | 89+2
 lw                             | 87
 lf                             | 89
 cf                             | 89
 rf                             | 89
 rw                             | 87
 lam                            | 88+3
 cam                            | 88+3
 ram                            | 88+3
 lm                             | 86+3
 lcm                            | 81+3
 cm                             | 81+3
 rcm                            | 81+3
 rm                             | 86+3
 lwb                            | 64+3
 ldm                            | 64+3
 cdm                            | 64+3
 rdm                            | 64+3
 rwb                            | 64+3
 lb                             | 60+3
 lcb                            | 55+3
 cb                             | 55+3
 rcb                            | 55+3
 rb                             | 60+3
 gk                             | 18+3
 player_face_url                | https://cdn.sofifa.net/players/165/153/23_120.png
only showing top 2 rows

### Bước 2: Kiểm tra cấu trúc, số lượng và dữ liệu mẫu

In [5]:
# Kiểm tra cấu trúc dữ liệu
df_male.printSchema()

# Kiểm tra các cột cần thiết cho ETL
columns_to_check = [
    "player_id", "short_name", "club_name",
    "nationality_name", "player_positions",
    "age", "overall", "potential",
    "wage_eur", "value_eur"
]

for c in columns_to_check:
    if c in df_male.columns:
        print(f"{c}: có trong dữ liệu")
    else:
        print(f"{c}: KHÔNG có trong dữ liệu")

root
 |-- player_id: integer (nullable = true)
 |-- player_url: string (nullable = true)
 |-- fifa_version: integer (nullable = true)
 |-- fifa_update: integer (nullable = true)
 |-- fifa_update_date: date (nullable = true)
 |-- short_name: string (nullable = true)
 |-- long_name: string (nullable = true)
 |-- player_positions: string (nullable = true)
 |-- overall: integer (nullable = true)
 |-- potential: integer (nullable = true)
 |-- value_eur: integer (nullable = true)
 |-- wage_eur: integer (nullable = true)
 |-- age: integer (nullable = true)
 |-- dob: date (nullable = true)
 |-- height_cm: integer (nullable = true)
 |-- weight_kg: integer (nullable = true)
 |-- league_id: integer (nullable = true)
 |-- league_name: string (nullable = true)
 |-- league_level: integer (nullable = true)
 |-- club_team_id: integer (nullable = true)
 |-- club_name: string (nullable = true)
 |-- club_position: string (nullable = true)
 |-- club_jersey_number: integer (nullable = true)
 |-- club_loaned_from: string (nullable = true)
 |-- club_joined_date: date (nullable = true)
 |-- club_contract_valid_until_year: integer (nullable = true)
 |-- nationality_id: integer (nullable = true)
 |-- nationality_name: string (nullable = true)
 |-- nation_team_id: integer (nullable = true)
 |-- nation_position: string (nullable = true)
 |-- nation_jersey_number: integer (nullable = true)
 |-- preferred_foot: string (nullable = true)
 |-- weak_foot: integer (nullable = true)
 |-- skill_moves: integer (nullable = true)
 |-- international_reputation: integer (nullable = true)
 |-- work_rate: string (nullable = true)
 |-- body_type: string (nullable = true)
 |-- real_face: string (nullable = true)
 |-- release_clause_eur: integer (nullable = true)
 |-- player_tags: string (nullable = true)
 |-- player_traits: string (nullable = true)
 |-- pace: integer (nullable = true)
 |-- shooting: integer (nullable = true)
 |-- passing: integer (nullable = true)
 |-- dribbling: integer (nullable = true)
 |-- defending: integer (nullable = true)
 |-- physic: integer (nullable = true)
 |-- attacking_crossing: integer (nullable = true)
 |-- attacking_finishing: integer (nullable = true)
 |-- attacking_heading_accuracy: integer (nullable = true)
 |-- attacking_short_passing: integer (nullable = true)
 |-- attacking_volleys: integer (nullable = true)
 |-- skill_dribbling: integer (nullable = true)
 |-- skill_curve: integer (nullable = true)
 |-- skill_fk_accuracy: integer (nullable = true)
 |-- skill_long_passing: integer (nullable = true)
 |-- skill_ball_control: integer (nullable = true)
 |-- movement_acceleration: integer (nullable = true)
 |-- movement_sprint_speed: integer (nullable = true)
 |-- movement_agility: integer (nullable = true)
 |-- movement_reactions: integer (nullable = true)
 |-- movement_balance: integer (nullable = true)
 |-- power_shot_power: integer (nullable = true)
 |-- power_jumping: integer (nullable = true)
 |-- power_stamina: integer (nullable = true)
 |-- power_strength: integer (nullable = true)
 |-- power_long_shots: integer (nullable = true)
 |-- mentality_aggression: integer (nullable = true)
 |-- mentality_interceptions: integer (nullable = true)
 |-- mentality_positioning: integer (nullable = true)
 |-- mentality_vision: integer (nullable = true)
 |-- mentality_penalties: integer (nullable = true)
 |-- mentality_composure: integer (nullable = true)
 |-- defending_marking_awareness: integer (nullable = true)
 |-- defending_standing_tackle: integer (nullable = true)
 |-- defending_sliding_tackle: integer (nullable = true)
 |-- goalkeeping_diving: integer (nullable = true)
 |-- goalkeeping_handling: integer (nullable = true)
 |-- goalkeeping_kicking: integer (nullable = true)
 |-- goalkeeping_positioning: integer (nullable = true)
 |-- goalkeeping_reflexes: integer (nullable = true)
 |-- goalkeeping_speed: integer (nullable = true)
 |-- ls: string (nullable = true)
 |-- st: string (nullable = true)
 |-- rs: string (nullable = true)
 |-- lw: string (nullable = true)
 |-- lf: string (nullable = true)
 |-- cf: string (nullable = true)
 |-- rf: string (nullable = true)
 |-- rw: string (nullable = true)
 |-- lam: string (nullable = true)
 |-- cam: string (nullable = true)
 |-- ram: string (nullable = true)
 |-- lm: string (nullable = true)
 |-- lcm: string (nullable = true)
 |-- cm: string (nullable = true)
 |-- rcm: string (nullable = true)
 |-- rm: string (nullable = true)
 |-- lwb: string (nullable = true)
 |-- ldm: string (nullable = true)
 |-- cdm: string (nullable = true)
 |-- rdm: string (nullable = true)
 |-- rwb: string (nullable = true)
 |-- lb: string (nullable = true)
 |-- lcb: string (nullable = true)
 |-- cb: string (nullable = true)
 |-- rcb: string (nullable = true)
 |-- rb: string (nullable = true)
 |-- gk: string (nullable = true)
 |-- player_face_url: string (nullable = true)

player_id: có trong dữ liệu
short_name: có trong dữ liệu
club_name: có trong dữ liệu
nationality_name: có trong dữ liệu
player_positions: có trong dữ liệu
age: có trong dữ liệu
overall: có trong dữ liệu
potential: có trong dữ liệu
wage_eur: có trong dữ liệu
value_eur: có trong dữ liệu

## PHẦN 3: LÀM SẠCH DỮ LIỆU VÀ CHUẨN HÓA DỮ LIỆU BẰNG SPARK
### Bước 1: Kiểm tra chất lượng dữ liệu khi làm sạch
Kiểm tra kiểu dữ liệu, giá trị thiếu và các trường thông tin quan trọng để xác định những vấn đề cần xử lý trước khi thực hiện ETL.

In [6]:
from pyspark.sql import functions as F
from pyspark.sql.types import StringType
# 1. Kiểm tra kiểu dữ liệu
df_male.printSchema()

# 2. Kiểm tra giá trị thiếu ở các cột quan trọng
key_cols = [
    c for c in [
        "player_id",
        "short_name",
        "club_name",
        "nationality_name",
        "player_positions",
        "age",
        "overall",
        "potential",
        "wage_eur",
        "value_eur"
    ]
    if c in df_male.columns
]
missing_stats = df_male.agg(*[
    F.sum(
        F.when(F.col(c).isNull(), 1).otherwise(0)
    ).alias(c)
    for c in key_cols
])
print("Số lượng giá trị NULL ở các cột quan trọng:")
missing_stats.show(truncate=False)

root
 |-- player_id: integer (nullable = true)
 |-- player_url: string (nullable = true)
 |-- fifa_version: integer (nullable = true)
 |-- fifa_update: integer (nullable = true)
 |-- fifa_update_date: date (nullable = true)
 |-- short_name: string (nullable = true)
 |-- long_name: string (nullable = true)
 |-- player_positions: string (nullable = true)
 |-- overall: integer (nullable = true)
 |-- potential: integer (nullable = true)
 |-- value_eur: integer (nullable = true)
 |-- wage_eur: integer (nullable = true)
 |-- age: integer (nullable = true)
 |-- dob: date (nullable = true)
 |-- height_cm: integer (nullable = true)
 |-- weight_kg: integer (nullable = true)
 |-- league_id: integer (nullable = true)
 |-- league_name: string (nullable = true)
 |-- league_level: integer (nullable = true)
 |-- club_team_id: integer (nullable = true)
 |-- club_name: string (nullable = true)
 |-- club_position: string (nullable = true)
 |-- club_jersey_number: integer (nullable = true)
 |-- club_loaned_from: string (nullable = true)
 |-- club_joined_date: date (nullable = true)
 |-- club_contract_valid_until_year: integer (nullable = true)
 |-- nationality_id: integer (nullable = true)
 |-- nationality_name: string (nullable = true)
 |-- nation_team_id: integer (nullable = true)
 |-- nation_position: string (nullable = true)
 |-- nation_jersey_number: integer (nullable = true)
 |-- preferred_foot: string (nullable = true)
 |-- weak_foot: integer (nullable = true)
 |-- skill_moves: integer (nullable = true)
 |-- international_reputation: integer (nullable = true)
 |-- work_rate: string (nullable = true)
 |-- body_type: string (nullable = true)
 |-- real_face: string (nullable = true)
 |-- release_clause_eur: integer (nullable = true)
 |-- player_tags: string (nullable = true)
 |-- player_traits: string (nullable = true)
 |-- pace: integer (nullable = true)
 |-- shooting: integer (nullable = true)
 |-- passing: integer (nullable = true)
 |-- dribbling: integer (nullable = true)
 |-- defending: integer (nullable = true)
 |-- physic: integer (nullable = true)
 |-- attacking_crossing: integer (nullable = true)
 |-- attacking_finishing: integer (nullable = true)
 |-- attacking_heading_accuracy: integer (nullable = true)
 |-- attacking_short_passing: integer (nullable = true)
 |-- attacking_volleys: integer (nullable = true)
 |-- skill_dribbling: integer (nullable = true)
 |-- skill_curve: integer (nullable = true)
 |-- skill_fk_accuracy: integer (nullable = true)
 |-- skill_long_passing: integer (nullable = true)
 |-- skill_ball_control: integer (nullable = true)
 |-- movement_acceleration: integer (nullable = true)
 |-- movement_sprint_speed: integer (nullable = true)
 |-- movement_agility: integer (nullable = true)
 |-- movement_reactions: integer (nullable = true)
 |-- movement_balance: integer (nullable = true)
 |-- power_shot_power: integer (nullable = true)
 |-- power_jumping: integer (nullable = true)
 |-- power_stamina: integer (nullable = true)
 |-- power_strength: integer (nullable = true)
 |-- power_long_shots: integer (nullable = true)
 |-- mentality_aggression: integer (nullable = true)
 |-- mentality_interceptions: integer (nullable = true)
 |-- mentality_positioning: integer (nullable = true)
 |-- mentality_vision: integer (nullable = true)
 |-- mentality_penalties: integer (nullable = true)
 |-- mentality_composure: integer (nullable = true)
 |-- defending_marking_awareness: integer (nullable = true)
 |-- defending_standing_tackle: integer (nullable = true)
 |-- defending_sliding_tackle: integer (nullable = true)
 |-- goalkeeping_diving: integer (nullable = true)
 |-- goalkeeping_handling: integer (nullable = true)
 |-- goalkeeping_kicking: integer (nullable = true)
 |-- goalkeeping_positioning: integer (nullable = true)
 |-- goalkeeping_reflexes: integer (nullable = true)
 |-- goalkeeping_speed: integer (nullable = true)
 |-- ls: string (nullable = true)
 |-- st: string (nullable = true)
 |-- rs: string (nullable = true)
 |-- lw: string (nullable = true)
 |-- lf: string (nullable = true)
 |-- cf: string (nullable = true)
 |-- rf: string (nullable = true)
 |-- rw: string (nullable = true)
 |-- lam: string (nullable = true)
 |-- cam: string (nullable = true)
 |-- ram: string (nullable = true)
 |-- lm: string (nullable = true)
 |-- lcm: string (nullable = true)
 |-- cm: string (nullable = true)
 |-- rcm: string (nullable = true)
 |-- rm: string (nullable = true)
 |-- lwb: string (nullable = true)
 |-- ldm: string (nullable = true)
 |-- cdm: string (nullable = true)
 |-- rdm: string (nullable = true)
 |-- rwb: string (nullable = true)
 |-- lb: string (nullable = true)
 |-- lcb: string (nullable = true)
 |-- cb: string (nullable = true)
 |-- rcb: string (nullable = true)
 |-- rb: string (nullable = true)
 |-- gk: string (nullable = true)
 |-- player_face_url: string (nullable = true)

Số lượng giá trị NULL ở các cột quan trọng:
+---------+----------+---------+----------------+----------------+---+-------+---------+--------+---------+
|player_id|short_name|club_name|nationality_name|player_positions|age|overall|potential|wage_eur|value_eur|
+---------+----------+---------+----------------+----------------+---+-------+---------+--------+---------+
|0        |0         |116395   |0               |0               |0  |0      |0        |115974  |132797   |
+---------+----------+---------+----------------+----------------+---+-------+---------+--------+---------+

### *Kết quả kiểm tra giá trị thiếu trong dữ liệu*

Sau khi thực hiện kiểm tra dữ liệu bằng Apache Spark, kết quả thống kê giá trị NULL trên 10 thuộc tính quan trọng của bộ dữ liệu cầu thủ nam FIFA cho thấy phần lớn các thuộc tính không có giá trị thiếu. Cụ thể, các cột `player_id`, `short_name`, `nationality_name`, `player_positions`, `age`, `overall` và `potential` đều có 0 giá trị NULL.

Tuy nhiên, một số thuộc tính vẫn tồn tại dữ liệu thiếu, bao gồm:

- **`club_name`:** có 116.395 giá trị NULL.
- **`wage_eur`:** có 115.974 giá trị NULL.
- **`value_eur`:** có 132.797 giá trị NULL.

Trong đó, `value_eur` là thuộc tính có số lượng giá trị thiếu lớn nhất trong các cột được kiểm tra. Những giá trị này có thể ảnh hưởng đến các phép thống kê về giá trị thị trường, tiền lương và phân tích theo câu lạc bộ nếu không được xem xé bằng Spark.

>**Kết luận:** Kết quả kiểm tra cho thấy dữ liệu có chất lượng tương đối tốt ở các thuộc tính định danh cầu thủ, quốc tịch, vị trí thi đấu, tuổi và các chỉ số năng lực. Tuy nhiên, vẫn tồn tại giá trị thiếu ở các thuộc tính liên quan đến câu lạc bộ và tài chính. Vì vậy, cần tiếp tục xử lý và chuẩn hóa dữ liệu ở bước tiếp theo trước khi thực hiện các phép tổng hợp, xây dựng bảng dữ liệu phụ và benchmark bằng Spark.

### Bước 2: Chuẩn hóa chuỗi và xử lý giá trị thiếu
Chuẩn hóa các cột kiểu chuỗi bằng cách loại bỏ khoảng trắng thừa ở đầu và cuối, đồng thời chuyển các chuỗi rỗng hoặc giá trị thiếu được biểu diễn bằng văn bản thành giá trị NULL thực sự.

In [7]:
from pyspark.sql import functions as F
from pyspark.sql.types import StringType

# Cột dùng ở các bảng phụ + cột phiên bản (nếu có) để khử trùng đúng
version_cols = [c for c in ["fifa_version", "fifa_update"] if c in df_male.columns]
keep_cols = [c for c in columns_to_check + version_cols if c in df_male.columns]
print("Các cột phiên bản tìm thấy:", version_cols)
print("Các cột được giữ lại:", keep_cols)

df_sel = df_male.select(*keep_cols)
string_cols = [f.name for f in df_sel.schema.fields
               if isinstance(f.dataType, StringType)]

def clean_str(c):
    v = F.trim(F.col(c))
    return (F.when(v.isNull() | (v == "")
                   | F.lower(v).isin("null", "none", "n/a", "na"),
                   F.lit(None).cast("string"))
             .otherwise(v).alias(c))

df_male_clean = df_sel.select(
    *[clean_str(c) if c in string_cols else F.col(c) for c in df_sel.columns]
)
print("Số cột kiểu chuỗi đã chuẩn hóa:", len(string_cols))
print("Đã hoàn thành bước chuẩn hóa chuỗi. Số cột còn lại:", len(df_male_clean.columns))

Các cột phiên bản tìm thấy: ['fifa_version', 'fifa_update']
Các cột được giữ lại: ['player_id', 'short_name', 'club_name', 'nationality_name', 'player_positions', 'age', 'overall', 'potential', 'wage_eur', 'value_eur', 'fifa_version', 'fifa_update']
Số cột kiểu chuỗi đã chuẩn hóa: 4
Đã hoàn thành bước chuẩn hóa chuỗi. Số cột còn lại: 12

**Đoạn code này xử lý các vấn đề sau:**

- Chỉ giữ lại **12 cột cần dùng** cho các bảng phụ (10 cột chính và 2 cột phiên bản `fifa_version`, `fifa_update`), giúp giảm dung lượng xử lý và dữ liệu tạm trên đĩa.
- Cắt khoảng trắng thừa ở đầu và cuối chuỗi: `" Paris Saint Germain "` → `"Paris Saint Germain"`.
- Chuỗi rỗng `""` → NULL.
- Chuỗi `"N/A"`, `"na"`, `"none"` hoặc `"null"` (không phân biệt hoa thường) → NULL.

Các giá trị thiếu được giữ lại dưới dạng NULL, chưa xoá hàng loạt. Đây là lựa chọn an toàn hơn với dữ liệu FIFA, vì một cầu thủ có thể thiếu câu lạc bộ hoặc lương nhưng vẫn có các thông tin khác hữu ích cho phân tích.

### Bước 3: Kiểm tra trùng lặp theo bộ khoá (`player_id`, `fifa_version`, `fifa_update`)

Mỗi bản ghi trong dữ liệu đại diện cho **một cầu thủ ở một phiên bản FIFA cụ thể**, nên một cầu thủ có thể xuất hiện nhiều lần hợp lệ qua các phiên bản. Vì vậy:

- **Không** loại trùng chỉ dựa trên `player_id`, vì sẽ xoá nhầm lịch sử của cùng một cầu thủ ở các phiên bản khác nhau.
- Bộ khoá để xác định một bản ghi là duy nhất gồm 3 cột: `player_id`, `fifa_version`, `fifa_update`.

Trước khi loại bỏ, ta **đếm số nhóm bị trùng theo bộ khoá này**. Cách này chỉ xáo trộn 3 cột nên nhẹ hơn nhiều so với `dropDuplicates()` trên toàn bộ cột, giúp hạn chế dữ liệu tạm ghi xuốt bản ghi. một bản ghi.

In [8]:
keys = ["player_id", "fifa_version", "fifa_update"]

dup_groups = (df_male_clean
              .groupBy(*keys).count()
              .filter(F.col("count") > 1)
              .count())
print("Số nhóm bị trùng theo khoá:", dup_groups)

Số nhóm bị trùng theo khoá: 0

### Bước 4: Chọn theo kết quả
- Nếu kết quả bằng 0: dữ liệu không có bản ghi trùng, không cần khử trùng.
- Nếu kết quả lớn hơn 0: dùng `dropDuplicates` theo bộ khoá trên, mỗi cầu thủ ở mỗi phiên bản chỉ giữ một bản ghi.

In [9]:
df_male_clean = df_male_clean.dropDuplicates(keys)
print("Đã loại bỏ bản ghi trùng lặp theo khoá:", keys)

Đã loại bỏ bản ghi trùng lặp theo khoá: ['player_id', 'fifa_version', 'fifa_update']

### Bước 5: Kiểm tra kết quả sau làm sạch

Kiểm tra số lượng bản ghi, cấu trúc dữ liệu và các giá trị thiếu sau khi chuẩn hóa. So sánh kết quả với dữ liệu ban đầu để đánh giá những thay đổi sau quá trình làm sạch.

In [10]:
from pyspark.sql import functions as F

# Chỉ lấy các cột quan trọng thực sự có trong dữ liệu đã làm sạch
key_cols = [c for c in columns_to_check if c in df_male_clean.columns]

# 1. Số dòng trước làm sạch (chỉ quét file, không xáo trộn nên rất nhẹ)
rows_before = df_male.count()

# 2. Số dòng sau làm sạch + đếm NULL: gộp thành MỘT lần chạy duy nhất
stats = df_male_clean.agg(
    F.count(F.lit(1)).alias("_rows"),
    *[F.sum(F.when(F.col(c).isNull(), 1).otherwise(0)).alias(c) for c in key_cols]
).collect()[0].asDict()

rows_after = stats.pop("_rows")

print(f"Số dòng trước làm sạch: {rows_before:,}")
print(f"Số dòng sau làm sạch:   {rows_after:,}")
print(f"Số dòng chênh lệch:      {rows_before - rows_after:,}")

# 3. Cấu trúc dữ liệu (chỉ đọc metadata, không tốn tài nguyên)
df_male_clean.printSchema()

# 4. Số lượng NULL ở các cột quan trọng
import pandas as pd
display(pd.DataFrame([stats]))

Số dòng trước làm sạch: 10,003,590
Số dòng sau làm sạch:   10,003,590
Số dòng chênh lệch:      0
root
 |-- player_id: integer (nullable = true)
 |-- short_name: string (nullable = true)
 |-- club_name: string (nullable = true)
 |-- nationality_name: string (nullable = true)
 |-- player_positions: string (nullable = true)
 |-- age: integer (nullable = true)
 |-- overall: integer (nullable = true)
 |-- potential: integer (nullable = true)
 |-- wage_eur: integer (nullable = true)
 |-- value_eur: integer (nullable = true)
 |-- fifa_version: integer (nullable = true)
 |-- fifa_update: integer (nullable = true)

,player_id,short_name,club_name,nationality_name,player_positions,age,overall,potential,wage_eur,value_eur
0,0,0,116395,0,0,0,0,0,115974,132797

In [11]:
# Chạy thử vài dòng
df_male_clean.limit(5).show(truncate=False)

+---------+-----------+--------------+----------------+----------------+---+-------+---------+--------+---------+------------+-----------+
|player_id|short_name |club_name     |nationality_name|player_positions|age|overall|potential|wage_eur|value_eur|fifa_version|fifa_update|
+---------+-----------+--------------+----------------+----------------+---+-------+---------+--------+---------+------------+-----------+
|2        |G. Pasquale|Udinese Calcio|Italy           |LM, LB          |32 |68     |68       |9000    |675000   |15          |1          |
|2        |G. Pasquale|Udinese       |Italy           |LM              |32 |68     |68       |9000    |675000   |15          |18         |
|2        |G. Pasquale|Udinese       |Italy           |LM              |32 |68     |68       |9000    |675000   |15          |28         |
|2        |G. Pasquale|Udinese       |Italy           |LM              |33 |69     |69       |7000    |625000   |16          |19         |
|2        |G. Pasquale|Udinese       |Italy           |LM              |33 |69     |69       |7000    |625000   |16          |23         |
+---------+-----------+--------------+----------------+----------------+---+-------+---------+--------+---------+------------+-----------+

### Kết quả kiểm tra dữ liệu sau làm sạch
Sau khi chọn lọc các cột cần dùng, chuẩn hóa chuỗi và loại bỏ bản ghi trùng lặp theo bộ khóa (**`player_id`**, **`fifa_version`**, **`fifa_update`**) bằng Apache Spark, dữ liệu được kiểm tra lại về số lượng bản ghi, cấu trúc các thuộc tính và số giá tri thiếu

**1. Kết quả so sánh số lượng bản ghi**
- Số dòng trước khi làm sạch: **10.003.590 dòng**
- Số dòng sau khi làm sạch: **10.003.590 dòng**
- Số dòng chênh lệch: **0 dòng**

> Số dòng không thay đổi nghĩa là không có bản ghi nào trùng nhau theo bộ khóa**`player_id`**, **`fifa_version`**, **`fifa_update`**. Mỗi bản ghi là một cầu thủ ở một phiên bản FIFA cụ thể, nên việc một cầu thủ xuất hiện nhiều lần qua các phiên bản là hợp lệ và được giữ nguyên. Bước chuẩn hóa chuỗi chỉ thay đổi giá trị bên trong bản ghi, không làm thay đổi số dòng.

**2. Kết quả kiểm tra giá trị thiếu (NULL)**
Kết quả `printSchema()` cho thấy dữ liệu sau làm sạch gồm **12 thuộc tính**:
- Kiểu số nguyên (`interger`): `player_id`, `age`, `overall`, `potential`, `wage_eur`, `valuje_eur`, `fifa_version`, `fifa_update`.
- Kiểu chuỗi (`string`): `short_name`, `club_name `, `nationality_name`, `player_positions`.

**3. Kết quả kiểm tra giá trị thiếu (NULL)**
|Thuộc tính|Số giá trị NULL|Tỷ lệ so với tổng số dòng|
|---|---|---
|`player_id`. `short_name`, `nationality_name`, `player_positions`, `age`, `overall`, `potential` | 0 | 0% |
|`club_name`|116.395|khoảng 1,16%|
|`wage_eur`|115.974|khoảng 1,16%$|
|`value_eur`|132.797|khoảng 1,33%|

Các thuộc tính dịnh danh và chỉ số chuyên môn đều đầy đủ. Giá trị thiếu chỉ tập trung ở `club_name`, `wage_eur` và `value_eur`, với tỷ lệ thấp (dưới 1,4%). Các giá trị này được giữ dưới dạng NULL, không xóa hàng loạt, vì cầu thủ thiếu câu lạc bộ hoặc lương vẫn có đầy đủ thông tin khác hữu ích cho phân tích.

**4. Kết luận**
- Quá trình làm sạch Spark đã chọn lọc 12 cột cần thiết, chuẩn hóa chuỗi và kiểm tra trùng lặp theo bộ khóa mà không làm thay đổi tổng số dòng (10.003.590).
- Cấu trúc dữ liệu rõ ràng, các kiểu dữ liệu phù hợp, tạo điều kiện thuận lợi cho các bước ETL tiếp theo như lọc cầu thủ và thống kê theo quốc tịch, câu lạc bộ, vị trí thi đấu.
- Các giá trị NULL ở `clunb_name`, `wage_eur`, `value_eur` cần được lưu ý khi tính toán thống kê. Các hàm tổng hợp của Spark như `avg` và `sum` tự bỏ qua giá trị NULL, nên không làm sai kết quả các bảng phụ.

## PHẦN 4: ETL VÀ XÂY DỰNG CÁC BẢNG DỮ LIỆU PHỤ

In [12]:
# Ghi dữ liệu sạch ra partque
df_male_clean.write.mode("overwrite").parquet(
    "hdfs://namenode:8020/fifa/tmp/male_clean"
)
df_male_clean = spark.read.parquet(
    "hdfs://namenode:8020/fifa/tmp/male_clean"
)

### Bước 1: Thực hiện các phép biến đổi ETL cơ bản trên Dataframe (df_male)
Bây giờ dữ liệu đã sẵn sàng trong biến df_male, bạn hãy tạo các ô code mới trong Jupyter để lọc, làm sạch và trích xuất thông tin theo yêu cầu của đồ án:
1. Lọc dữ liệu cầu thủ có chỉ số tiềm năng cao (Potential >= 85):

In [13]:
# Lọc các cầu thủ có tiềm năng từ 85 trở lên
top_potential_players = df_male_clean.filter(
    F.col("potential") >= 85
)

print(
    "Số lượng cầu thủ tiềm năng cao:",
    top_potential_players.count()
)

top_potential_players.select(
    "short_name",
    "club_name",
    "overall",
    "potential"
).show(5, truncate=False)

Số lượng cầu thủ tiềm năng cao: 189739
+----------+------------+-------+---------+
|short_name|club_name   |overall|potential|
+----------+------------+-------+---------+
|Iniesta   |FC Barcelona|89     |89       |
|Iniesta   |FC Barcelona|89     |89       |
|Iniesta   |FC Barcelona|89     |89       |
|Iniesta   |FC Barcelona|88     |88       |
|Iniesta   |FC Barcelona|88     |88       |
+----------+------------+-------+---------+
only showing top 5 rows

2. Tạo bảng

In [14]:
from pyspark.sql import functions as F, Window

# Phiên bản FIFA mới nhất trong dữ liệu
latest_version = df_male_clean.agg(F.max("fifa_version")).collect()[0][0]
print("Phiên bản mới nhất:", latest_version)

# Mỗi cầu thủ chỉ giữ lần cập nhật cuối cùng của phiên bản đó
w = Window.partitionBy("player_id").orderBy(F.col("fifa_update").desc())

df_latest = (
    df_male_clean
    .filter(F.col("fifa_version") == latest_version)
    .withColumn("rn", F.row_number().over(w))
    .filter(F.col("rn") == 1)
    .drop("rn")
    .persist()      # bảng rất nhỏ, giữ trong bộ nhớ cho các cell sau
)

print("Số cầu thủ (mỗi người một dòng):", df_latest.count())

Phiên bản mới nhất: 23
Số cầu thủ (mỗi người một dòng): 20621

3. Tính toán thống kê nhóm (Group By): Ví dụ tính số cầu thủ, tuổi trung bình, chỉ số overall trung bình và tổng giá trị thị trường (value_eur) theo từng quốc gia (nationality_name), trên dữ liệu phiên bản FIFA mới nhất (mỗi cầu thủ một bản ghi).

In [15]:
from pyspark.sql import functions as F

# 1. Tính toán thống kê nhóm và đặt tên alias
nationality_stats = (df_latest.groupBy("nationality_name")
    .agg(
        F.count("player_id").alias("total_players"),
        F.avg("overall").alias("avg_overall"),
        F.sum("value_eur").alias("total_value")
    )
    .orderBy(F.col("total_value").desc())
    .cache())

# 2. Hiển thị 10 quốc gia dẫn đầu
nationality_stats.show(10, truncate=False)

+----------------+-------------+------------------+-----------+
|nationality_name|total_players|avg_overall       |total_value|
+----------------+-------------+------------------+-----------+
|Spain           |1184         |68.59037162162163 |5265890000 |
|France          |1007         |67.22244289970209 |4572820000 |
|Brazil          |771          |71.22178988326849 |4308490000 |
|England         |1805         |63.282548476454295|4059420000 |
|Germany         |1274         |65.58084772370486 |3528040000 |
|Argentina       |1074         |68.1219739292365  |3167210000 |
|Italy           |711          |67.43881856540085 |2735925000 |
|Portugal        |404          |69.48267326732673 |2478050000 |
|Netherlands     |471          |67.18046709129511 |1976820000 |
|Belgium         |349          |66.63323782234957 |1263875000 |
+----------------+-------------+------------------+-----------+
only showing top 10 rows

### Bước 2: Tạo và lưu các bảng phụ (Auxiliary Tables)
Trong các yêu cầu của đồ án Big Data, việc tạo các bảng phụ tổng hợp (ví dụ: thống kê theo CLB, theo quốc tịch, hoặc theo vị trí) giúp tối ưu hóa truy vấn sau này. Bạn có thể lưu các bảng phụ này xuống định dạng Parquet (định dạng tối ưu nhất cho Spark) trên HDFS:

In [16]:
# BẢNG PHỤ 1: THỐNG KÊ THEO QUỐC TỊCH
nationality_stats = (
    df_latest
    .groupBy("nationality_name")
    .agg(
        F.count("player_id").alias("total_players"),
        F.avg("age").alias("avg_age"),
        F.avg("overall").alias("avg_overall"),
        F.sum("value_eur").alias("total_value")
    )
    .orderBy(F.col("total_value").desc())
)
nationality_stats.show(10, truncate=False)

+----------------+-------------+------------------+------------------+-----------+
|nationality_name|total_players|avg_age           |avg_overall       |total_value|
+----------------+-------------+------------------+------------------+-----------+
|Spain           |1184         |25.21114864864865 |68.59037162162163 |5265890000 |
|France          |1007         |24.43992055610725 |67.22244289970209 |4572820000 |
|Brazil          |771          |26.78988326848249 |71.22178988326849 |4308490000 |
|England         |1805         |24.065373961218835|63.282548476454295|4059420000 |
|Germany         |1274         |24.5447409733124  |65.58084772370486 |3528040000 |
|Argentina       |1074         |25.931098696461824|68.1219739292365  |3167210000 |
|Italy           |711          |25.873417721518987|67.43881856540085 |2735925000 |
|Portugal        |404          |24.730198019801982|69.48267326732673 |2478050000 |
|Netherlands     |471          |23.976645435244162|67.18046709129511 |1976820000 |
|Belgium         |349          |23.78223495702006 |66.63323782234957 |1263875000 |
+----------------+-------------+------------------+------------------+-----------+
only showing top 10 rows

### Bước 3: Tối ưu hóa (Optimization) & Benchmark
Caching / Persisting: Khi bạn thực hiện nhiều thao tác lặp đi lặp lại trên DataFrame lớn (như df_male), hãy dùng lệnh cache để giữ nó trên bộ nhớ RAM, giúp các câu lệnh chạy nhanh hơn ở những lần gọi sau:

In [17]:
print(spark)

<pyspark.sql.session.SparkSession object at 0x742044dc78d0>

In [18]:
# Lấy 5 dòng đầu tiên và hiển thị dưới dạng bảng trực quan
display(df_male_clean.limit(5).toPandas())

,player_id,short_name,club_name,nationality_name,player_positions,age,overall,potential,wage_eur,value_eur,fifa_version,fifa_update
0,2,G. Pasquale,Udinese,Italy,LM,32,68,68,9000,675000,15,14
1,2,G. Pasquale,Udinese,Italy,LM,32,68,68,9000,675000,15,19
2,2,G. Pasquale,Udinese,Italy,"LM, LB",32,69,69,10000,675000,15,38
3,2,G. Pasquale,Udinese,Italy,LM,33,69,69,7000,625000,16,33
4,2,G. Pasquale,Udinese,Italy,LM,33,69,69,7000,625000,16,36

In [19]:
# Benchmark thời gian chạy:
# Đo thời gian thực thi của truy vấn lớn bằng time.perf_counter().
# Kết quả giúp đánh giá hiệu suất xử lý dữ liệu của PySpark.
import time
from pyspark.sql.functions import avg

start = time.perf_counter()

df_male_clean.groupBy("club_name") \
    .agg(avg("wage_eur").alias("avg_wage")) \
    .show(10)

end = time.perf_counter()

print(f"Thời gian thực thi: {end - start:.2f} giây")

+---------------+------------------+
|      club_name|          avg_wage|
+---------------+------------------+
|  Coventry City| 5161.929317067035|
|  Leyton Orient| 3311.795218764096|
|   Grimsby Town| 2197.794481258036|
|       Alcorcón| 4800.777815353399|
|    Real Madrid|139740.27214823393|
|         Grödig| 3102.861562258314|
|AFC Bournemouth|26211.219663269327|
|      Feyenoord|14628.237560192616|
|         Chaves|5582.4492011788425|
|     PEC Zwolle| 5273.468407912425|
+---------------+------------------+
only showing top 10 rows

Thời gian thực thi: 2.24 giây

### Bước 4: Tạo bảng phụ theo câu lạc bộ
Bảng này giúp trả lời những câu hỏi như:
- Câu lạc bộ nào có tổng giá trị thị trường cầu thủ cao?
- Câu lạc bộ nào có mức lương trung bình cao?
- Chất lượng cầu thủ trung bình giữa các câu lạc bộ khác nhau thế nào?

In [20]:
# BẢNG PHỤ 2: Thống kê cầu thủ theo câu lạc bộ
club_stats = (
    df_latest
    .filter(F.col("club_name").isNotNull())      # bỏ nhóm không có câu lạc bộ
    .groupBy("club_name")
    .agg(
        F.count("player_id").alias("total_players"),
        F.avg("overall").alias("avg_overall"),
        F.avg("wage_eur").alias("avg_wage"),
        F.sum("value_eur").alias("total_value")
    )
    .orderBy(F.col("total_value").desc())
)
club_stats.show(10, truncate=False)

+-------------------+-------------+-----------------+------------------+-----------+
|club_name          |total_players|avg_overall      |avg_wage          |total_value|
+-------------------+-------------+-----------------+------------------+-----------+
|Manchester City    |26           |79.53846153846153|141076.92307692306|1255055000 |
|Liverpool          |59           |72.13559322033899|55795.76271186441 |1138045000 |
|Paris Saint Germain|26           |80.34615384615384|87826.92307692308 |1056575000 |
|Real Madrid        |33           |76.9090909090909 |129318.18181818182|1031050000 |
|FC Barcelona       |37           |75.91891891891892|100216.21621621621|1020625000 |
|FC Bayern München  |27           |78.44444444444444|61296.2962962963  |1004750000 |
|Chelsea            |35           |76.82857142857142|86142.85714285714 |959525000  |
|Inter              |28           |78.5             |60785.71428571428 |744025000  |
|Manchester United  |33           |76.06060606060606|85666.66666666667 |737850000  |
|Milan              |32           |77.28125         |53906.25          |697450000  |
+-------------------+-------------+-----------------+------------------+-----------+
only showing top 10 rows

### Bước 5: Tạo bảng phụ theo vị trí thi đấu
Lưu ý: player_positions có thể chứa nhiều vị trí trong cùng một ô, chẳng hạn RW, ST. Khi đó, kết quả đang thống kê theo chuỗi vị trí được ghi trong dữ liệu, chưa tách riêng từng vị trí.

In [21]:
# BẢNG PHỤ 3: Thống kê theo vị trí thi đấu
position_stats = (
    df_latest
    .groupBy("player_positions")
    .agg(
        F.count("player_id").alias("total_players"),
        F.avg("overall").alias("avg_overall"),
        F.avg("potential").alias("avg_potential"),
        F.avg("value_eur").alias("avg_value")
    )
    .orderBy(F.col("total_players").desc())
)
position_stats.show(10, truncate=False)

+----------------+-------------+------------------+-----------------+------------------+
|player_positions|total_players|avg_overall       |avg_potential    |avg_value         |
+----------------+-------------+------------------+-----------------+------------------+
|CB              |2679         |65.90182904068682 |70.73684210526316|2540618.1886508833|
|GK              |2311         |63.96841194288187 |69.44872349632193|1779923.2446576536|
|ST              |1937         |65.08569953536397 |70.21889519876098|2648788.351534061 |
|CDM, CM         |1050         |67.19047619047619 |71.34571428571428|3027390.0573613765|
|CM              |798          |61.728070175438596|69.7468671679198 |2554611.528822055 |
|CM, CDM         |762          |67.03937007874016 |71.47637795275591|3490732.1899736146|
|LB              |552          |64.84601449275362 |69.8713768115942 |2401047.3588342443|
|RB              |534          |64.82771535580524 |69.93258426966293|2250844.2776735458|
|CB, RB          |310          |65.96129032258065 |70.74193548387096|2912806.4516129033|
|CDM             |303          |62.62376237623762 |68.85478547854785|1978576.1589403974|
+----------------+-------------+------------------+-----------------+------------------+
only showing top 10 rows

### Bước 6: Lưu các bảng phụ lên HDFS dưới dạng Parquet
Lưu 3 bảng phụ theo quốc tịch, câu lạc bộ và vị trí thi đấu

In [22]:
# Lưu 3 bảng phụ lên HDFS dưới dạng Parquet
nationality_stats.write.mode("overwrite").parquet("hdfs://namenode:8020/fifa/processed/nationality_summary")
club_stats.write.mode("overwrite").parquet("hdfs://namenode:8020/fifa/processed/club_summary")
position_stats.write.mode("overwrite").parquet("hdfs://namenode:8020/fifa/processed/position_summary")

print("Đã lưu 3 bảng phụ lên HDFS!")

Đã lưu 3 bảng phụ lên HDFS!

In [23]:
# Kiểm tra các thư mục đã lưu. Nếu kết quả đều là True, các thư mục tương ứng đang tồn tại trên HDFS.
spark._jsc.hadoopConfiguration().get("fs.defaultFS")

hdfs = spark._jvm.org.apache.hadoop.fs.FileSystem.get(
    spark._jsc.hadoopConfiguration()
)

for path in [
    "/fifa/processed/nationality_summary",
    "/fifa/processed/club_summary",
    "/fifa/processed/position_summary"
]:
    print(path, "->", hdfs.exists(
        spark._jvm.org.apache.hadoop.fs.Path(path)
    ))

/fifa/processed/nationality_summary -> True
/fifa/processed/club_summary -> True
/fifa/processed/position_summary -> True

## PHẦN 5: TỐI ƯU HÓA BẰNG CACHE VÀ BENCHMARK
### Bước 1: Đo thời gian truy vấn trước khi cache

In [24]:
import time

# Benchmark trước khi cache
start = time.perf_counter()

df_male_clean.groupBy("club_name").agg(
    F.avg("wage_eur").alias("avg_wage")
).show(10)

time_before_cache = time.perf_counter() - start

print(f"Thời gian trước cache: {time_before_cache:.2f} giây")

+---------------+------------------+
|      club_name|          avg_wage|
+---------------+------------------+
|  Coventry City| 5161.929317067035|
|  Leyton Orient| 3311.795218764096|
|   Grimsby Town| 2197.794481258036|
|       Alcorcón| 4800.777815353399|
|    Real Madrid|139740.27214823393|
|         Grödig| 3102.861562258314|
|AFC Bournemouth|26211.219663269327|
|      Feyenoord|14628.237560192616|
|         Chaves|5582.4492011788425|
|     PEC Zwolle| 5273.468407912425|
+---------------+------------------+
only showing top 10 rows

Thời gian trước cache: 1.28 giây

### Bước 2: Cache DataFrame và đo lại 
df_male.count() được dùng để kích hoạt việc tính toán và nạp DataFrame vào cache trước khi đo truy vấn. Vì vậy, thời gian nạp dữ liệu ban đầu không nằm trong thời gian benchmark thứ hai.

Lưu ý: Cache có thể làm truy vấn lặp lại nhanh hơn, nhưng không đảm bảo lúc nào cũng nhanh hơn. Kết quả còn phụ thuộc vào RAM, tài nguyên cụm, dữ liệu và tải hệ thống.

In [25]:
from pyspark import StorageLevel

# Lưu DataFrame vào bộ nhớ để tái sử dụng (không ghi xuống đĩa)
df_male_clean.persist(StorageLevel.MEMORY_ONLY)

# Kích hoạt việc đọc và lưu dữ liệu vào cache
df_male_clean.count()

# Benchmark sau khi cache
start = time.perf_counter()

df_male_clean.groupBy("club_name").agg(
    F.avg("wage_eur").alias("avg_wage")
).show(10)

time_after_cache = time.perf_counter() - start

print(f"Thời gian sau cache: {time_after_cache:.2f} giây")

+---------------+------------------+
|      club_name|          avg_wage|
+---------------+------------------+
|  Coventry City| 5161.929317067035|
|  Leyton Orient| 3311.795218764096|
|   Grimsby Town| 2197.794481258036|
|       Alcorcón| 4800.777815353399|
|    Real Madrid|139740.27214823393|
|         Grödig| 3102.861562258314|
|AFC Bournemouth|26211.219663269327|
|      Feyenoord|14628.237560192616|
|         Chaves|5582.4492011788425|
|     PEC Zwolle| 5273.468407912425|
+---------------+------------------+
only showing top 10 rows

Thời gian sau cache: 1.22 giây

### Bước 3: Tính mức cải thiện hiệu suất 
Nếu phần trăm dương, thời gian chạy giảm; nếu phần trăm âm, thời gian chạy tăng. Để kết quả đáng tin cậy hơn, bạn nên chạy mỗi trường hợp vài lần và so sánh các lần chạy tương ứng, vì lần chạy đầu có thể chịu ảnh hưởng của việc khởi tạo Spark và đọc dữ liệu từ HDFS.

In [26]:
import pandas as pd
from IPython.display import display

# Tính mức cải thiện hiệu suất
if time_before_cache > 0:
    improvement = (
        (time_before_cache - time_after_cache)
        / time_before_cache
    ) * 100

    # Tạo bảng kết quả benchmark
    benchmark_results = pd.DataFrame({
        "Chỉ tiêu": [
            "Thời gian trước khi cache",
            "Thời gian sau khi cache",
            "Mức cải thiện hiệu suất"
        ],
        "Giá trị": [
            f"{time_before_cache:.2f} giây",
            f"{time_after_cache:.2f} giây",
            f"{improvement:.2f}%"
        ]
    })

    display(benchmark_results)

# Giải phóng cache, tránh hiển thị DataFrame dài
_ = df_male_clean.unpersist()

print("Đã giải phóng cache thành công.")

                    Chỉ tiêu    Giá trị
0  Thời gian trước khi cache  1.28 giây
1    Thời gian sau khi cache  1.22 giây
2    Mức cải thiện hiệu suất      5.02%

Đã giải phóng cache thành công.

## PHẦN 6: KIỂM TRA KẾT QUẢ VÀ TỔNG KẾT

In [27]:
# Kiểm tra đọc lại 3 bảng phụ từ HDFS

nationality_check = spark.read.parquet(
    "hdfs://namenode:8020/fifa/processed/nationality_summary"
)

club_check = spark.read.parquet(
    "hdfs://namenode:8020/fifa/processed/club_summary"
)

position_check = spark.read.parquet(
    "hdfs://namenode:8020/fifa/processed/position_summary"
)

# Hiển thị số dòng của từng bảng
print("Số dòng bảng quốc tịch:", nationality_check.count())
print("Số dòng bảng câu lạc bộ:", club_check.count())
print("Số dòng bảng vị trí:", position_check.count())

Số dòng bảng quốc tịch: 165
Số dòng bảng câu lạc bộ: 673
Số dòng bảng vị trí: 728

## TỔNG KẾT

- **Nhiệm vụ:** Xử lý dữ liệu bằng Apache Spark, xây dựng các bảng dữ liệu phụ, tối ưu hóa quá trình xử lý và đánh giá hiệu suất thực thi truy vấn.

- **Đọc và làm sạch dữ liệu:** Thiết lập kết nối giữa Spark và HDFS, đọc dữ liệu cầu thủ nam từ tệp `male_players.csv` vào Spark DataFrame (10.003.590 bản ghi, mỗi bản ghi là một cầu thủ ở một lần cập nhật của một phiên bản FIFA). Dữ liệu được chọn lọc 12 cột cần thiết, chuẩn hóa chuỗi (cắt khoảng trắng, chuyển chuỗi rỗng và giá trị như "N/A", "null" thành NULL) và kiểm tra trùng lặp theo bộ khoá `player_id`, `fifa_version`, `fifa_update`. Kết quả không phát hiện bản ghi trùng, số dòng giữ nguyên 10.003.590. Dữ liệu sạch được lưu ra HDFS dưới dạng Parquet để các bước sau đọc nhanh và tiết kiệm tài nguyên.

- **Bảng dữ liệu phụ:** Các bảng phụ được tính trên phiên bản FIFA mới nhất (`fifa_version` = [...]), mỗi cầu thủ lấy một bản ghi ở lần cập nhật cuối, nhằm tránh cộng dồn giá trị của cùng một cầu thủ qua nhiều phiên bản. Gồm ba bảng theo quốc tịch ([165] dòng), câu lạc bộ ([673] dòng) và vị trí thi đấu ([728] dòng), cung cấp số lượng cầu thủ, chỉ số tổng thể trung bình, mức lương trung bình, chỉ số tiềm năng trung bình và giá trị thị trường theo từng nhóm. Các bảng được lưu trên HDFS dưới định dạng Parquet và đã được đọc lại để kiểm tra.

- **Tối ưu hiệu suất:** Sử dụng cơ chế cache của Spark ([persist với MEMORY_ONLY]) để lưu DataFrame vào bộ nhớ khi thực hiện các thao tác lặp lại. Benchmark truy vấn tính mức lương trung bình theo câu lạc bộ cho kết quả: trước cache [...] giây, sau cache [...] giây, mức thay đổi [...]%. Vì dữ liệu đã được lưu dạng Parquet với số cột ít nên truy vấn gốc vốn đã nhanh, do đó mức cải thiện của cache nhỏ hơn so với khi đọc trực tiếp từ CSV. Sau benchmark, cache được giải phóng bằng `unpersist()`.

> Nhìn chung, nhiệm vụ Spark ETL đã thực hiện được các nội dung chính gồm đọc và xử lý dữ liệu, tạo các bảng phụ phục vụ truy vấn phân tích, lưu trữ dữ liệu tổng hợp dưới định dạng Parquet trên HDFS và đánh giá hiệu suất thông qua benchmark. Kết quả góp phần chuẩn bị dữ liệu có cấu trúc cho các bước khai thác và phân tích tiếp theo của dự án Big Data.